# Generated by Django 4.2.5 on 2023-09-27 15:47

from django.db import migrations

def inserir_gênero_inicial(apps, schema_editor):
    Gênero = apps.get_model('filmes_app', 'Gênero')
    Gênero.objects.create(descrição='Romance')
    

class Migration(migrations.Migration):

    dependencies = [
        ('filmes_app', '0002_gênero'),
    ]

    operations = [
        migrations.RunPython(inserir_gênero_inicial)
    ]
