# Generated by Django 4.2.5 on 2023-10-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_app', '0003_inserir_gênero_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='gênero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filmes_app.gênero'),
            preserve_default=False,
        ),
    ]
